steps:
  # Build docker image for target sub-package
  - name: gcr.io/cloud-builders/docker
    id: Build Image
    env:
      - 'NEXT_PUBLIC_ENV=${BRANCH_NAME}'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Copy root files and workspace packages for monorepo build
        cp yarn.lock Dockerfile .dockerignore prettier.config.js packages/$_TARGET_PACKAGE/
        # Copy root configs separately to avoid overwriting package's own configs
        cp package.json packages/$_TARGET_PACKAGE/root-package.json
        cp .eslintrc.js packages/$_TARGET_PACKAGE/root-eslintrc.js
        cp -r packages/draft-renderer packages/$_TARGET_PACKAGE/
        cd packages/$_TARGET_PACKAGE
        printenv > .env.local
        docker build -t gcr.io/$PROJECT_ID/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA} .

  # Push docker image
  - name: gcr.io/cloud-builders/docker
    id: Push Image
    args:
      - push
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA}'

  # Deploy container image to Cloud Run with Secrets
  - name: gcr.io/cloud-builders/gcloud
    id: Deploy Image
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Determine secret suffix based on branch
        case "${BRANCH_NAME}" in
          main|master|prod) SECRET_SUFFIX="_PROD" ;;
          staging)          SECRET_SUFFIX="_STAGING" ;;
          *)                SECRET_SUFFIX="_DEV" ;;
        esac

        echo "Deploying with secrets suffix: $SECRET_SUFFIX"

        # Read cloud run service names from substitution variable
        IFS=',' read -r -a cloud_runs <<< "$_CLOUD_RUN_SERVICE_NAMES"

        for cr in "${cloud_runs[@]}"
        do
          echo "Deploying to Cloud Run service: $cr"

          gcloud run deploy "$cr" \
            --image gcr.io/$PROJECT_ID/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA} \
            --region asia-east1 \
            --update-secrets="FIREBASE_ADMIN_PROJECT_ID=FIREBASE_ADMIN_PROJECT_ID${SECRET_SUFFIX}:latest,FIREBASE_ADMIN_CLIENT_EMAIL=FIREBASE_ADMIN_CLIENT_EMAIL${SECRET_SUFFIX}:latest,FIREBASE_ADMIN_PRIVATE_KEY=FIREBASE_ADMIN_PRIVATE_KEY${SECRET_SUFFIX}:latest,TURNSTILE_SECRET_KEY=TURNSTILE_SECRET_KEY${SECRET_SUFFIX}:latest,MAILCHIMP_API_KEY=MAILCHIMP_API_KEY${SECRET_SUFFIX}:latest,MAILCHIMP_LIST_ID=MAILCHIMP_LIST_ID${SECRET_SUFFIX}:latest"

        done

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s

images: ['gcr.io/$PROJECT_ID/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA}']

substitutions:
  _TARGET_PACKAGE: ''
  _IMAGE_NAME: ''
  _CLOUD_RUN_SERVICE_NAMES: ''
